# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TCPClient' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TCPClient
	pod 'MessageKit'


  target 'TCPClientTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TCPClientUITests' do
    # Pods for testing
  end

end
